# Generated by Django 5.0.2 on 2024-02-25 11:38

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('first_stage_body', wagtail.fields.RichTextField(blank=True, help_text='Content for the first stage of the room')),
                ('second_stage_body', wagtail.fields.RichTextField(blank=True, help_text='Content for the second stage of the room')),
                ('unlock_key', models.CharField(help_text='Key to unlock the room', max_length=255)),
                ('second_stage_unlock_key', models.CharField(help_text='Key to unlock the second stage content', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
