# Generated by Django 5.0.2 on 2024-02-25 12:44

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roompage'),
    ]

    operations = [
        migrations.AddField(
            model_name='roompage',
            name='first_stage_unlock_error_message',
            field=models.TextField(default='Incorrect password for the first stage.'),
        ),
        migrations.AddField(
            model_name='roompage',
            name='first_stage_unlock_success_message',
            field=models.TextField(default='First stage successfully unlocked!'),
        ),
        migrations.AddField(
            model_name='roompage',
            name='second_stage_unlock_error_message',
            field=models.TextField(default='Incorrect password for the second stage.'),
        ),
        migrations.AddField(
            model_name='roompage',
            name='second_stage_unlock_success_message',
            field=models.TextField(default='Second stage successfully unlocked!'),
        ),
        migrations.AlterField(
            model_name='roompage',
            name='first_stage_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='roompage',
            name='second_stage_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='roompage',
            name='second_stage_unlock_key',
            field=models.CharField(blank=True, help_text='Key to unlock the second stage content (leave blank if not required)', max_length=255),
        ),
        migrations.AlterField(
            model_name='roompage',
            name='unlock_key',
            field=models.CharField(blank=True, help_text='Key to unlock the room (leave blank if not required)', max_length=255),
        ),
    ]
